FROM captainsparrow/allure-generator:2.13.1-s3


RUN apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/main libuv &&\
    apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-current-npm
RUN node --version
